### ISSUE TITLE
Recurso en español de machine learning

### ISSUE THREAD

**Issue by JavierMoralesEstevez** [ml-hispano/recursos#12]
Hola,
Quiero compartir el siguiente recurso con la comunidad:

- Título: Recursos de afshinea
- Enlace: [enlace](https://github.com/afshinea/stanford-cs-229-machine-learning/tree/master/es)
- Tipo: Papers
- Descripción: Hojas de referencia de Machine Learning (CS 229 Stanford) en español

**Comment by andfk** [comment]
Hecho @JavierMoralesEstevez gracias por inaugurar esta manera de añadir recursos. Ya está añadido el Paper.
