### ISSUE TITLE
Curso intensivo de aprendizaje automático

### ISSUE THREAD

**Issue by JavierMoralesEstevez** [ml-hispano/recursos#13]
Hola,
Quiero compartir el siguiente recurso con la comunidad:

- Título: Curso intensivo de aprendizaje automático
- Enlace: [enlace](https://developers.google.com/machine-learning/crash-course/)
- Tipo: Curso
- Descripción: Curso intensivo de aprendizaje automático de Google.

pd: En realidad ya está copiado, pero indica que está en inglés y está en español.

**Comment by andfk** [comment]
De acuerdo, he actualizado el recurso. Gracias!
