### ISSUE TITLE
Documentos de conocimiento general

### ISSUE THREAD

**Issue by santiagomj** [ml-hispano/recursos#14]
Hola,
Quiero compartir el siguiente recurso con la comunidad:

- Título: Lesiones de estadística y técnicas de clasificación.
- Enlace: [enlace](http://wwwae.ciemat.es/~cardenas/docs/lessons/)
- Tipo: Papers
- Descripción: Conocimiento general en estadística y técnicas de clasificación en español aplicables a machine learning,

**Comment by JavierMoralesEstevez** [comment]
Santiago éste enlace ya está añadido, son los de Ciemat, aunque tu descripción es mejor ;)

**Comment by andfk** [comment]
Hecho! Muchas gracias :)
