### ISSUE TITLE
Curso introductorio impartido por DotCSV

### ISSUE THREAD

**Issue by JavierMoralesEstevez** [ml-hispano/recursos#15]
Hola,
Quiero compartir el siguiente recurso con la comunidad:

- Título: Curso introductorio impartido por DotCSV
- Enlace: [enlace](https://github.com/dotcsv/Intro-ML-course)
- Tipo: Cursos
- Descripción: Curso de "Introducción al aprendizaje automático" que impartió DotCSV en noviembre de 2018. Los ejercicios van desde modelos simples, como la regresión lineal hasta técnicas más avanzadas como las redes neuronales convolucionales.

**Comment by jenniferarevalom** [comment]
Hola Chicos , pueden aperturar nuevamente el enlace por favor . 
Estoy recopilando información para la elaboración de mi tesis .
jennifer.arevalom@gmail.com

Muy Amables
