### ISSUE TITLE
¿Cómo saber si está usando una IA?

### ISSUE THREAD

**Issue by serome111** [ml-hispano/recursos#17]
Hola,
Quiero compartir el siguiente recurso con la comunidad:

- Título: ¿Cómo saber si está usando una IA? 
- Enlace: [enlace](https://www.technologyreview.es/s/10738/como-saber-si-esta-usando-una-ia-descubralo-con-este-grafico?fbclid=IwAR0jBC2HooVH9RXiOIT77b84OTCa14mLZWEd06FJVAgc6ZIlh1b7snTwAoI)
- Tipo: Artículo/Blog
- Descripción: ¿Cómo saber si está usando una IA? Descúbralo con este gráfico

**Comment by andfk** [comment]
Gracias @serome111. He preguntado a la comunidad si añadimos una carpeta con artículos dado que este recurso aún no clasifica para añadirlo, estoy a la espera :)
