### ISSUE TITLE
Falta agregar el código de conducta en: https://github.com/ml-hispano/recursos/community/code-of-conduct/new

### ISSUE THREAD

**Issue by lalohrndz** [ml-hispano/recursos#26]
Aqui esta el md del código, solamente falta pasarlo a dónde se especifica.
[https://github.com/ml-hispano/recursos/blob/master/C%C3%93DIGO_DE_CONDUCTA.md]

**Comment by andfk** [comment]
Dónde dices que debería ir? No te acabo de entender, lo siento @lalohrndz

**Comment by lalohrndz** [comment]
Aquí -->
https://github.com/ml-hispano/recursos/community

**Comment by andfk** [comment]
@lalohrndz entendido. Por algún motivo que desconozco no lo está detectando correctamente, al igual que los templates de los issues que también están creados. Te agradezco de todas formas.
