### ISSUE TITLE
Fases del proceso de Machine Learning

### ISSUE THREAD

**Issue by jmartinezheras** [ml-hispano/recursos#33]
Hola,
Quiero compartir el siguiente recurso con la comunidad:

- Título: Fases del proceso de Machine Learning
- Enlace: [enlace](https://iartificial.net/fases-del-proceso-de-machine-learning/)
- Tipo: Artículos/Blog
- Descripción: Para obtener buenos resultados en Machine Learning, debemos seguir este proceso.
- Idioma: ES

**Comment by andfk** [comment]
Muchas gracias @jmartinezheras
