### ISSUE TITLE
Lista actualizada de Blogs de IA en español

### ISSUE THREAD

**Issue by jmartinezheras** [ml-hispano/recursos#36]
Hola,
Quiero compartir el siguiente recurso con la comunidad:

- Título: Blogs de Inteligencia Artificial y Machine Learning
- Enlace: [enlace](https://iartificial.net/blogs-de-inteligencia-artificial-y-machine-learning/)
- Tipo: Artículo/Blog
- Descripción: Lista actualizada de Blogs en español sobre Inteligencia Artificial, Machine Learning y Análisis de Datos
- Idioma: ES

**Comment by ianholing** [comment]
Added 👍
